### ISSUE TITLE
Error while running the example  

### ISSUE THREAD

**Issue by hhp2020** [iotauth/iotauth#3]
Hi, 

while i tried to run the example code i faced the following error in second stage running auth-server:

Exception in thread "main" java.lang.IllegalArgumentException: No such JS crypto algorithm: undefined
	at org.iot.auth.crypto.SymmetricKeyCryptoSpec.fromJSCryptoAlgo(SymmetricKeyCryptoSpec.java:176)
	at org.iot.auth.crypto.SymmetricKeyCryptoSpec.fromSpecString(SymmetricKeyCryptoSpec.java:63)
	at org.iot.auth.db.RegisteredEntity.<init>(RegisteredEntity.java:90)
	at org.iot.auth.db.AuthDB.lambda$loadRegEntityDB$0(AuthDB.java:354)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.iot.auth.db.AuthDB.loadRegEntityDB(AuthDB.java:345)
	at org.iot.auth.db.AuthDB.initialize(AuthDB.java:77)
	at org.iot.auth.AuthServer.<init>(AuthServer.java:112)
	at org.iot.auth.AuthServer.main(AuthServer.java:286)

can you help please 
thanks

**Comment by hokeun** [comment]
Thank you for reporting the issue. I'm looking into this, however, I cannot reproduce this error. Could you please let me know under what environment you're running the examples? Thanks.

**Comment by hokeun** [comment]
@hhp2020, this issue should have been addressed after recent code cleanups. Could you please try building auth-server again? Please re-open this issue if the error persists. Thanks!
