### ISSUE TITLE
Error in latest prerequisite version when ./generateAll.sh

### ISSUE THREAD

**Issue by Jakio815** [iotauth/iotauth#9]
Getting error in ./generateAll. 

`[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
child_process.js:656
    throw err;
    ^

Error: Command failed: mvn -pl example-auth-db-generator -am install -DskipTests
    at checkExecSyncError (child_process.js:635:11)
    at execFileSync (child_process.js:653:15)
    at Object.<anonymous> (/home/dongha/project/iotauth/examples/authDBGenerator.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1565353,
  stdout: null,
  stderr: null
}
[Error] Script finished with problems! exiting...
`

-node version 
12.22.12

-maven version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.3, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-100-generic", arch: "amd64", family: "unix"

-java version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

**Comment by hokeun** [comment]
I believe this error was addressed since the recent code cleanups.
